### PR TITLE
added option to exclude a list of prefixes.

### PR DESCRIPTION
**Pull request by NieTiger**
Some external sites intentionally mess up crawler responses (e.g., linkedin) so it'll be nice to have the option to exclude them in config. I have no way of testing this code though so please let me know if I did it right or if I should make changes.

Also changed [`require` to `required`which is the proper keyword](https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions). I know different issues should be in different PRs but this is so trivial and doesn't change anything as `required` defaults to `false.

### CODE REVIEW

**Comment by ScholliYT** [comment]
Thanks for the info and PR 😄 I just notices some minor things needed to change. First of all Variables have to be prefixed like `INPUT_<VARIABLE_NAME>` in the python script. Additionally a example (like in the Readme) would be nice. The `excluded_link_prefixes` collection was originally meant to exclude other protocols like "mailto:" links. However, if you provide links in the format of "https://www.linkedin.com/" to the `excluded_link_prefixes` collection, these will also be blocked.

**Comment by ScholliYT** [comment]
I also added a section on how to run this action locally with docker. Check that out for your testing: https://github.com/ScholliYT/Broken-Links-Crawler-Action/blob/master/README.md#dev

**Comment by NieTiger** [comment]
Decided with comma separated list. Updated readme

**Comment by ScholliYT** [comment]
It works! Nice work. I just adjusted some minior things like a default value for `exclude_url_prefix` and some docs. Thank you @NieTiger 😄

**Pull request merged**
