### PR TITLE
Feature/fixing action

### PR DESCRIPTION
**Pull request by aceberle**
This is an attempt at fixing issue #10 where the action fails on GitHub workflow with the following message:

`/usr/local/bin/python: Error while finding module specification for 'deadseeker.action' (ModuleNotFoundError: No module named 'deadseeker')`

I'm not certain why the module would not be found, but I have modified the Dockerfile to use relative paths when copying files into the image in this pull request.  I guess that even though docker can run the image just fine when GitHub runs the image it must do something to the current working directory which prevents the files from being found.

### CODE REVIEW

**Comment by ScholliYT** [comment]
looks like this does not fix the problem. I did a run with v3.0.1-beta which failed again: https://github.com/ScholliYT/devportfolio/runs/2666156970?check_suite_focus=true

**Comment by aceberle** [comment]
Hi @ScholliYT, this is very weird and difficult to figure out since it only presents the problem when it is actually run as a workflow action.   I have swapped out the "CMD" command with "ENTRYPOINT" in the Dockerfile -- I'm hoping this will prevent github workflow from somehow overriding the command

**Comment by aceberle** [comment]
Hi @ScholliYT, I think I've figured it out -- when GitHub workflow runs, it uses the "--workdir" parameter to change the working directory inside of the docker container to "/github/workspace".  When the container tries to execute the command, the current working directory is "/github/workspace" instead of staying in the current working directory for the container ("/" by default).  So I need to be very specific where I put the python code and then add that to the PYTHONPATH environment variable so that python can find the module no matter what the current working directory is.  Working on this now...

**Comment by aceberle** [comment]
Okay, this time I am really sure it is fixed.  I was able to reproduce the issue locally by running the image with --workdir="/opt/", and then verify that the latest changes fix the issue

**Comment by aceberle** [comment]
I added the --workdir="/opt/" argument to the github action so that we would catch this if it ever happened again

**Comment by ScholliYT** [comment]
This does the trick. Thank you for figuring it out so quick. What a weird behavior.

**Pull request merged**
