### PR TITLE
Feature/enhance testing and concur requests

### PR DESCRIPTION
**Pull request by aceberle**
Hi @ScholliYT, here's everything from before and the additional features I mentioned earlier:
1) allow the ability to always GET for onsite URLs
2) allow the ability to throttle requests, in case the server has rate limiting enabled

I also refactored the tests so that everything now has a unit test and I turned the original deadseeker test into an integration test

### CODE REVIEW

**Comment by ScholliYT** [comment]
So this replaces #7. I'll give this a try and start writing a changelog.

**Comment by aceberle** [comment]
> So this replaces #7. I'll give this a try and start writing a changelog.

Yes that's correct -- I'm not sure why I couldn't find #7, but this has everything that branch had and then some more

**Comment by aceberle** [comment]
Hi Tom, let me know if there is anything I can do to help with the change log

**Comment by ScholliYT** [comment]
Hi Adam, I didn't have time to test your new changes. If you have the time to write a changelog (maybe migration guide) feel free to do so 😊

**Comment by ScholliYT** [comment]
One thing I noticed is that the versions of dependencies in `requirements.txt` are not locked. IMO we should lock these so this action wont break accidentally. I can also configure Dependabot so I can keep packages up to date (regarding security patches).

Another thing I noticed is that the time displayed after the requests in verbose mode seems to accumulate per site
image

Also links like `../../page/site.html` don't work. This however is a thing I would not include in the next release. It's something good for a upcoming feature update.

**Comment by aceberle** [comment]
> the versions of dependencies in requirements.txt are not locked

That is a great point, I will update with exact values

> the time displayed after the requests in verbose mode seems to accumulate per site

Oh weird, okay I will take a look

**Comment by aceberle** [comment]
Hi @ScholliYT, please let me know the inputs that you used to produce the screenshot you provided, I want to make sure that I am recreating the scenario accurately.  I will check to see how the original code behaved because this may be correct behavior: if we asynchronously start multiple requests, but your web server only handles a certain number of requests at once, then the requests will be queued.  As each request is handled, then we will see the elapsed time increase as your screenshot indicates.

**Comment by ScholliYT** [comment]
You're right! I tried that one with `INPUT_MAX_CONCURRENT_REQUESTS=1` 🤦‍♂️

**Comment by aceberle** [comment]
> I tried that one with INPUT_MAX_CONCURRENT_REQUESTS=1

I actually didn't even think about that having an impact, I'm glad you figured that out (and I'm glad that feature is working)!

**Comment by ScholliYT** [comment]
Haha, nice. I think I tried most of the features now. I started writing some changelog notes which I'll post here once finished.

**Comment by aceberle** [comment]
Hi Tom, while investigating the aiohttp API for a better way to track request elapsed time, I discovered that this module already supports throttling requests by limiting the number of simultaneous TCP connections per host.  I modified the code yesterday to use the built-in mechanism instead of the custom logic that I wrote to handle the same task.

This caused me to change the setting name from INPUT_MAX_CONCURRENT_REQUESTS to INPUT_CONNECT_LIMIT_PER_HOST to better describe the effect on the application.

I haven't quite figured out the best way to capture the request elapsed time.  Right now the timer starts before any of the aiohttp logic begins, which can cause confusing elapsed time values because the elapsed time includes the amount of time the request might wait while queued up to acquire the connection, and it also includes any additional time spent retrying a failed request.   I was considering modifying this so that the timer would start right after the request has acquired the connection, which would more accurately track the time the server took to service a single request.  But if you think that it is desirable to include retry and queue time in the elapsed time value in the log, then I will leave it.  I guess it depends on what you think the objective of the elapsed time value is.  If elapsed time just contains request time, then users can use it to measure server response time.  But if elapsed time contains queue time and retry time, then users can use it to measure the effectiveness of their inputs for the app -- For example, they can use this information to figure out if deadseeker is spending too much time on retries, then they can reduce the max retries.  Or if requests are spending too much time sitting in the queue, they will see this and increase the connection limit.  I am curious to hear your perspective and desired approach to calculating elapsed time.

**Comment by ScholliYT** [comment]
Thanks again @aceberle  for all these changes. I just changed one more line and merged this as v3.0.0

**Comment by aceberle** [comment]
Hey @ScholliYT thats great news.  Thanks for letting me participate in your project and I hope we can work again soon

**Comment by ScholliYT** [comment]
I bet there are some improvements to be made soon.  just curious, did this program work out for your cache filling application?

**Pull request merged**
