### PR TITLE
Fix for timeouts, head not supported, relative links

### LINKED ISSUE #4: Only check http / https links

### LINKED ISSUE #5: Some relative links detected as broken false positive
I do not have time to figure out what was causing it, but as a word of warning I was having _some_ but relative links getting falsely detected as broken.

Rather than fix it, I just changed to root-relative links for them and deadseeker stopped complaining.

### LINKED ISSUE #8: Images often cause HTTP Error 405: Method Not Allowed
Running this action on some websites with images the HTTP HEAD Request causes some `HTTP Error 405: Method Not Allowed` errors for the image urls. We should fall back to HTTP GET if HTTP HEAD fails.

### LINKED ISSUE #12: Timeouts are not handled well
Since moving to the asynchronous implementation, the code defaults to using an unlimited amount of connections to fetch all of the URLs.  This can occasionally overwhelm the server and cause timeout exceptions to be thrown.  Additionally, the timeout exceptions are not caught and are not retried, so the action run fails with a stack like the following:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/modules/deadseeker/action.py", line 58, in <module>
    run_action()
  File "/modules/deadseeker/action.py", line 52, in run_action
    if(len(seeker.seek(urls, responsehandler).failures, ) > 0):
  File "/modules/deadseeker/deadseeker.py", line 105, in seek
    results = asyncio.run(self._main(url_list, responsehandler))
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/modules/deadseeker/deadseeker.py", line 70, in _main
    resp = await task
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 619, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/modules/deadseeker/responsefetcher.py", line 42, in fetch_response
    await self._inner_fetch(session, resp, urltarget, timer)
  File "/modules/deadseeker/responsefetcher.py", line 104, in _inner_fetch
    await super()._inner_fetch(
  File "/modules/deadseeker/responsefetcher.py", line 72, in _inner_fetch
    async with session.head(url) as headresponse:
  File "/usr/local/lib/python3.8/site-packages/aiohttp_retry/__init__.py", line 186, in __aenter__
    return await self._do_request()
  File "/usr/local/lib/python3.8/site-packages/aiohttp_retry/__init__.py", line 180, in _do_request
    raise e
  File "/usr/local/lib/python3.8/site-packages/aiohttp_retry/__init__.py", line 152, in _do_request
    response: ClientResponse = await self._request(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/usr/local/lib/python3.8/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

The default timeout value for aiohttp is 5 minutes, so it takes a while before the failure occurs.

**Expected behavior**
The expected behavior would be for the logic to handle the timeout exception just like any other: it should simply log that an exception occurred and consider the link to be "bad".   Additionally, if any retry settings are configured, then the logic should retry the call if a timeout occurs.   It would also be nice to allow the ability to configure the timeout value and default it to something lower than 5 minutes.

### PR DESCRIPTION
**Pull request by aceberle**
Fixes #12 
Fixes #5 
Fixes #8 
Fixes #4 

- Catches all exceptions during requests so that the program does not just fail
- Allows request timeout value to be specified, defaults to 60 seconds
- Logic now defaults to 10 connections per host instead of infinity, to reduce the potential for timeouts to occur
- Timeout exceptions are now retried, if applicable

### CODE REVIEW

**Comment by ScholliYT** [comment]
This is looking good so far. Just ping me when you're finished.

`Catches all exceptions during requests so that the program does not just fail` is also something I noticed. This is very helpful.

**Comment by aceberle** [comment]
Will do!  I think I'm going to add one more feature -> enable link resolution before applying the filtering criteria, which would mean that links would be fully resolved to their absolute location before checking to see if they should be accepted based on the include/exclude rules.   By default, the logic will do what it has always done, so there will be a setting to allow you to enable this behavior.  I will let you know when it's ready!

**Comment by aceberle** [comment]
Hi @ScholliYT , I believe I've added everything I needed for this pass.  Please review at your convenience

**Comment by ScholliYT** [comment]
Thanks for the changes 👍  I merged them now as `v3.1.0`

**Comment by banagale** [comment]
Well done, @aceberle!

**Pull request merged**
